### PR TITLE
fix: Update generateSecretKey from account-export package

### LINKED ISSUE #680: Exporting accounts using secure URL format fails with TypeError (crypto module)
I've started testing out the account export implementation with Meteor today and ran into this issue:

```
Uncaught TypeError: crypto.randomBytes is not a function
    at getNextRandomValue (generate.js:11:24)
    at randomNumber (generate.js:23:13)
    at generate (generate.js:49:20)
    at module.exports.generate (generate.js:138:17)
    at generateSecretKey (index.js:4946:43)

Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at getNextRandomValue (generate.js:9:62)
    at randomNumber (generate.js:23:13)
    at generate (generate.js:49:20)
    at module.exports.generate (generate.js:138:17)
    at generateSecretKey (index.js:4946:43)
    at index.js:5005:17

The above error occurred in the <Passphrase> component:

    at Passphrase (http://localhost:4200/node_modules/.vite/deps/@near-wallet-selector_account-export.js?v=d2207208:4506:3)
    at ExportAccount (http://localhost:4200/node_modules/.vite/deps/@near-wallet-selector_account-export.js?v=d2207208:4713:3)
```

It appears to be an issue with the `generate-password` library (https://github.com/brendanashworth/generate-password) which is used to generate the secret key to encrypt the user's accounts and private keys for exports:

```ts
export const generateSecretKey = (): string =>
  generator.generate({
    length: nacl.secretbox.keyLength,
    numbers: true,
    strict: true,
    lowercase: true,
    uppercase: true,
    symbols: true,
  });
```

On their docs, they say that it is not browser compatible (since they `require()` a Node.js module), which means it can't serve our purposes here. They do mention a browser-compatible version of their library though: https://www.npmjs.com/package/generate-password-browser.

But- I'm not really sure why we are adding this as a dependency though? The Near API JS library already has the ability to generate random keys on the fly, right? :

```ts
import { KeyPair } from "near-api-js";

const randomKey = KeyPair.fromRandom("ed25519").getPublicKey().toString();
```

Could that not serve our purposes here?

### PR DESCRIPTION
**Pull request by hcho112**
# Description

Fixes #680 

This PR contains implementation for changing `generateSecretKey` interface of account-export.
1. Removed  `generate-password` package
2. Update `generateSecretKey` to use `tweetnacl.randomBytes`
3. Minor update on `importAccount.spec` tests

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# Type of change.

- [x] FIX - a PR of this type patches a bug.
- [ ] FEATURE - a PR of this type introduces a new feature.
- [ ] BUILD - a PR of this type introduces build changes.
- [ ] CI - a PR of this type introduces CI changes.
- [ ] DOCS - a PR of this type introduces DOCS improvement.
- [ ] STYLE - a PR of this type introduces style changes.
- [ ] REFACTOR - a PR of this type introduces refactoring.
- [ ] PERFORMANCE - a PR of this type introduces performance changes.
- [ ] TEST - a PR of this type adds more tests.
- [ ] CHORE - a PR introduces other changes than the specified above.

### CODE REVIEW

File: packages/account-export/src/lib/helpers/importAccount.ts [hunk 1]
```diff
@@ -74,12 +73,7 @@ export const decryptAccountData = ({
...
-    length: nacl.secretbox.keyLength,
-    numbers: true,
-    strict: true,
-    lowercase: true,
-    uppercase: true,
-    symbols: true,
-  });
+export const generateSecretKey = (): string => {
+  const random = nacl.randomBytes(nacl.secretbox.keyLength);
+  return encodeBase64(random).substring(0, 32);
```
Comment (hcho112) [inline packages/account-export/src/lib/helpers/importAccount.ts:78]: @andy-haynes I would like to get your feedback on here!
While I spent time on using `nacl` to generate 32 character secret key, I couldn't figure out and  ended up using `substring` to enforce the character size to 32. Do you know more elegant solution on this?

Comment (andy-haynes) [reply packages/account-export/src/lib/helpers/importAccount.ts:78]: The byte array contains wider (2^8) values than base 64 (2^6), so encoding in base 64 requires more symbols to represent the same amount of information. The length of the encoded string is always 44, with the last character being `=` for padding.  So the byte array of length 32 represents up to `(2^8)^32 = 256^32 = 1.2e77` values and a base 64 string of length 43 is `(2^6)^43 = 64^43 = 4.6e77`, making 43 the lowest number of base 64 characters you can use to represent all values in the byte array.

To get a 32 character base 64 string, you need a byte array of length `log_256(64^32) = 24` (https://www.wolframalpha.com/input?i=log+base+256+%2864%5E32%29). We should be able to rely on that to always produce strings of length 32 😄

Comment (andy-haynes) [reply packages/account-export/src/lib/helpers/importAccount.ts:78]: Also the byte array of length 32 always had a `=` padding character because 32 is not a multiple of 3. A byte array of length 24 is a multiple of 3 and so will never contain padding, so we will always make the most of our 32 characters.

https://en.wikipedia.org/wiki/Base64#Output_padding

> Because Base64 is a six-bit encoding, and because the decoded values are divided into 8-bit octets, every four characters of Base64-encoded text (4 sextets = 4 × 6 = 24 bits) represents three octets of unencoded text or data (3 octets = 3 × 8 = 24 bits). This means that when the length of the unencoded input is not a multiple of three, the encoded output must have padding added so that its length is a multiple of four. The padding character is =, which indicates that no further bits are needed to fully encode the input.

Comment (hcho112) [reply packages/account-export/src/lib/helpers/importAccount.ts]: @andy-haynes awesome! thank you for guidance and explanation!

**Review by andy-haynes — APPROVED** [review]
🚀
